'use strict';
const RollingPanel=(()=>{
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const pct=x=>x==null?'—':(x*100).toFixed(1)+'%',num=x=>x==null?'—':x.toFixed(3),metrics=g=>QplHistoryEngine.metrics(g);
 function metricRow(label,g){const m=metrics(g);return '<tr><td>'+esc(label)+'</td><td>'+g.evaluated.toLocaleString()+' / '+g.total.toLocaleString()+'</td><td>'+pct(m.rate)+'</td><td>'+(m.average==null?'—':m.average.toFixed(2))+'</td><td>'+num(m.product)+'</td></tr>';}
 const table=rows=>'<div class="table-scroll"><table class="validation-table"><thead><tr><th>구분</th><th>평가 / 전체</th><th>적중률</th><th>평균배당</th><th>곱</th></tr></thead><tbody>'+rows+'</tbody></table></div>';
 async function init(apply){const root=document.querySelector('#rollingReport'),button=document.querySelector('#applyRolling'),status=document.querySelector('#rollingStatus');
  try{const response=await fetch('rolling-report.json?v=7.0&t='+Date.now(),{cache:'no-store'});if(!response.ok)throw Error('검증 자료 HTTP '+response.status);const r=await response.json();if(r.schema!==1||r.version!==TuningModel.VERSION||!r.folds?.length||r.minimumCoverageRatio<.4)throw Error('반복 검증 자료 형식을 확인해 주세요.');
   const config=StrategyPresets.config(r.live.settings);if(r.folds.some(f=>f.selected.evaluated<Math.ceil(f.selected.total*.4))||r.live.retrospective.all.evaluated<Math.ceil(r.sourceRaces*.4))throw Error('전체 경주 40% 조건 확인 필요');
   root.innerHTML='<p class="hint">'+esc(r.from)+' ~ '+esc(r.to)+' · '+r.folds.length+'개 분기 · 전체 자료 '+r.sourceRaces.toLocaleString()+'경주<br>이전 24·36개월 중 마지막 3개월로 선택 → 다음 3개월 평가</p>'+table(metricRow('공통 가중치',r.common.all)+metricRow('경마장별 가중치',r.regional.all)+metricRow('분기 전 선택 방식',r.selected.all))+'<p class="hint">분기 전 선택 방식의 일마감 최대 낙폭: 베팅액의 '+r.selected.maxDrawdown.toFixed(1)+'배. 각 분기에 선택했던 조합을 연결한 성적이며 아래 현재 설정의 과거 재계산과 다릅니다.</p><details><summary>보정 기록 방식 비교</summary>'+table(r.recordComparison.map(x=>metricRow(x.label,x.all)).join(''))+'<p class="hint">각 방식의 가중치와 학습기간은 해당 분기 이전 자료로 선택했습니다. 기록 혼합에는 기록 변동성 지표도 포함됩니다.</p></details><details><summary>분기별 평가와 선택 기준</summary>'+table(r.folds.map(f=>metricRow(f.from.slice(0,4)+'년 '+(Math.floor((+f.from.slice(4,6)-1)/3)+1)+'분기'+(f.partial?' (진행중)':''),f.selected)).join(''))+'<p class="hint">'+r.folds.map(f=>esc(f.from)+' · '+f.months+'개월 · '+esc(f.style)+' · '+(f.choice==='venue'?'경마장별':'공통')).join('<br>')+'</p></details><p><strong>현재 분기: '+(config.weightScope==='venue'?'경마장별 가중치':'전국 공통 가중치')+' · '+esc(r.live.style)+'</strong><br>'+(config.anchorMode==='analysis'?'분석 1위':'최종배당 1위')+' 축마 · 배당 '+config.min+'~'+config.max+'위</p><details><summary>현재 가중치와 경마장별 표본</summary><div class="table-scroll"><table class="validation-table"><thead><tr><th>지표</th><th>공통</th><th>서울</th><th>부경</th><th>제주</th></tr></thead><tbody>'+TuningModel.FEATURES.map((f,i)=>'<tr><td>'+esc(f.label)+'</td><td>'+config.weights[i]+'%</td>'+['seoul','busan','jeju'].map(v=>'<td>'+(config.venueWeights?.[v]?.[i]??config.weights[i])+'%</td>').join('')+'</tr>').join('')+'</tbody></table></div><p class="hint">'+Object.entries(r.live.venueSupport).map(([v,x])=>esc(({seoul:'서울',busan:'부경',jeju:'제주'})[v])+' · 탐색 '+x.trainingRaces+'경주 / 선택 '+x.selectionRaces+'경주'+(x.fallback?' · 공통 가중치 사용':' · 지역 후보 반영률 '+pct(x.shrinkage))).join('<br>')+'</p></details><p class="hint">'+esc(r.note)+'</p>';
   button.hidden=false;button.onclick=()=>{const saved=apply(config);document.querySelector('#presetName').value='반복 검증 '+r.live.forQuarter;status.textContent='현재 분기 선택 조합을 불러왔습니다.'+(saved?' 이름을 정해 설정을 저장할 수 있습니다.':' 자동 저장에는 실패했습니다.');};
  }catch(e){root.textContent='반복 검증 결과를 불러오지 못했습니다. 새로고침 후 다시 확인해 주세요.';status.textContent=e.message;}
 }
 return {init};
})();
if(typeof module!=='undefined')module.exports=RollingPanel;
