'use strict';
const Top5Panel=(()=>{
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),pct=x=>(x*100).toFixed(2)+'%';
 async function init(apply,refresh){
  const root=document.querySelector('#top5Presets'),status=document.querySelector('#top5Status');
  try{
   const response=await fetch('top5-presets.json?v=analysis-rank-1-'+Date.now(),{cache:'no-store'});if(!response.ok)throw Error();const r=await response.json();
   const originalFrom=r.from;
   r.presets=r.presets.map(p=>{const all=QplHistoryEngine.sumYears(p.years,QplHistoryEngine.PERIOD.from),recent=QplHistoryEngine.sumYears(p.years,QplHistoryEngine.PERIOD.comparisonFrom);return {...p,all,metrics:QplHistoryEngine.metrics(all),coverage:all.total?all.evaluated/all.total:0,comparison:{all:recent,metrics:QplHistoryEngine.metrics(recent)},years:Object.fromEntries(Object.entries(p.years).filter(([year])=>year>=QplHistoryEngine.PERIOD.from.slice(0,4)))};});
   r.from=QplHistoryEngine.PERIOD.from;r.sourceRaces=r.presets[0]?.all.total||0;r.minimumEvaluated=Math.ceil(r.sourceRaces*.4);
   if(r.scope!=='seoul'||r.version!==TuningModel.VERSION||r.presets?.length!==1||!r.weightBalance||r.presets.some(p=>p.settings.weights.some(w=>w<3||w>20))||r.presets.some(p=>p.all.evaluated<Math.ceil(r.sourceRaces*.4)||p.all.hits*20<p.all.evaluated*3))throw Error();
   const configs=r.presets.map(p=>StrategyPresets.config(p.settings));
   try{if(StrategyPresets.replaceGenerated(localStorage,r.presets.map((p,i)=>({name:p.name,settings:configs[i]})),r.generatedAt+'-single-1')){refresh();status.textContent='이전 추천을 정리하고 1번 프리셋만 저장했습니다.';}}catch(e){status.textContent='자동 저장하지 못했습니다. '+e.message;}
   root.innerHTML='<p class="hint">'+esc(r.from)+' ~ '+esc(r.to)+' · 서울 '+r.sourceRaces.toLocaleString()+'경주<br>각 말의 최근 5경주 기준 · 17개 지표<br>최소 '+r.minimumEvaluated.toLocaleString()+'경주(40%) 이상 평가 · 적중률 15% 이상<br>1번 프리셋만 유지<br>모든 항목 3~20% · 최근 성적 20~40% · 기록 최대 35% · 컨디션 최대 20%</p><p class="hint">1번 프리셋을 2022년 이후로 재평가한 성적입니다. 순위·가중치를 새로 탐색한 결과는 아닙니다. 새 기간에서 최고 조합을 찾으려면 자동 탐색을 이용하세요.</p>'+r.presets.map((p,i)=>{const c=configs[i],m=p.metrics;return '<article class="preset-candidate"><h3>'+esc(p.name)+' · '+m.product.toFixed(3)+'배</h3><p><strong>'+'연승확률 분석 '+(c.anchorRank||1)+'위 축마 · 두 번째 말 분석 '+c.min+'~'+c.max+'위</strong></p><p>적중률 '+pct(m.rate)+' × 평균 적중배당 '+m.average.toFixed(2)+'배<br>적중 '+p.all.hits.toLocaleString()+' / 평가 '+p.all.evaluated.toLocaleString()+'경주 · 전체의 '+pct(p.coverage)+'<br>원선정 기간의 프리셋 간 선택 차이 최소 '+pct(p.nearestPairDifference)+'<br>기준 '+p.baseId+'번 계열 · 항목별 '+p.weightSummary.minimum+'~'+p.weightSummary.maximum+'%</p><button type="button" data-top5="'+i+'">프리셋 '+p.rank+' 적용·저장</button><details><summary>17개 가중치 보기</summary><table class="validation-table"><thead><tr><th>요소</th><th>가중치</th></tr></thead><tbody>'+TuningModel.FEATURES.map((f,j)=>'<tr><td>'+esc(f.label)+'</td><td>'+c.weights[j]+'%</td></tr>').join('')+'</tbody></table><p class="hint">'+p.weightSummary.groups.map(g=>esc(g.label)+' '+g.weight+'%').join(' · ')+'</p></details><details><summary>연도별 성적</summary><table class="validation-table"><thead><tr><th>연도</th><th>평가 / 전체</th><th>곱</th></tr></thead><tbody>'+Object.entries(p.years).map(([year,g])=>'<tr><td>'+esc(year)+'</td><td>'+g.evaluated+' / '+g.total+'</td><td>'+(QplHistoryEngine.metrics(g).product?.toFixed(3)??'—')+'</td></tr>').join('')+'</tbody></table></details>'+HistorySummary.comparison(p.comparison)+'</article>';}).join('')+'<details><summary>기준 프리셋 정보</summary><p class="hint">'+r.bases.map(b=>'기준 '+b.id+'번 · '+'연승확률 분석 '+(b.settings.anchorRank||1)+'위 축마 · 분석 '+b.settings.min+'~'+b.settings.max+'위').join('<br>')+'</p></details><p class="hint">'+'원선정 기간 '+esc(originalFrom)+' ~ '+esc(r.to)+'의 가중치를 보관한 프리셋입니다. 불러오면 2022년 이후 과거 통계가 다시 계산됩니다.</p>';
   const saveAll=document.querySelector('#saveAllTopPresets');saveAll.hidden=false;saveAll.onclick=()=>{try{StrategyPresets.replaceGenerated(localStorage,r.presets.map((p,i)=>({name:p.name,settings:configs[i]})),r.generatedAt+'-single-1',true);refresh();status.textContent='1번 프리셋을 저장했습니다. 현재 적용된 설정은 유지됩니다.';}catch(e){status.textContent='일괄 저장하지 못했습니다. '+e.message;}};
   root.addEventListener('click',event=>{const button=event.target.closest('[data-top5]');if(!button)return;const i=Number(button.dataset.top5);if(!Number.isInteger(i)||!configs[i])return;apply(configs[i]);document.querySelector('#presetName').value=r.presets[i].name;document.querySelector('#saveStrategy').onclick();status.textContent=r.presets[i].name+'을 적용했습니다. '+document.querySelector('#presetStatus').textContent;});
  }catch{root.textContent='1번 프리셋을 불러오지 못했습니다. 새로고침해 주세요.';}
 }
 return {init};
})();
