const assert=require('node:assert/strict'),{pairDistance,weightDistance}=require('../scripts/preset-diversity.cjs'),p=require('../strategy-presets.js');
assert.equal(pairDistance([0,1,2,3],[0,1,4,3]),1/3);assert.equal(pairDistance([0,1],[1,0]),1);assert.equal(pairDistance([0,0],[0,0]),0);
assert.equal(weightDistance([100,0],[0,100]),1);assert.equal(weightDistance([50,50],[55,45]),.05);
const store={data:{},getItem(k){return this.data[k]||null},setItem(k,v){this.data[k]=v}},settings={modelMode:'custom',anchorMode:'odds',weights:Array(16).fill(1),min:2,max:4};
p.saveMany(store,[{name:'old',settings}]);p.saveMany(store,Array.from({length:10},(_,i)=>({name:'preset '+i,settings})));assert.equal(p.read(store).length,11);const before=JSON.stringify(store.data);assert.throws(()=>p.saveMany(store,[{name:'invalid',settings:{...settings,weights:[0]}}]));assert.equal(JSON.stringify(store.data),before);
console.log('PASS prediction distance excludes joint omissions, weight distance and atomic bulk preset save preserves existing settings');

const base={...settings,weights:[...Array(16).fill(1),0]};const oldNames=['서울 10% 분산 3번','서울 10% 분산 4번','서울 10% 분산 9번','서울 10% 분산 1번','서울 과거 최고 1위'];p.saveMany(store,oldNames.map(name=>({name,settings:base})));const batch=Array.from({length:15},(_,i)=>({name:'서울 5경주 기준3 파생 '+(i+1)+'번',settings:base}));const customCount=p.read(store).filter(x=>!oldNames.includes(x.name)).length;p.replaceGenerated(store,batch,'r1');assert.equal(p.read(store).length,customCount+15);assert(!p.read(store).some(x=>oldNames.includes(x.name)));assert.equal(p.replaceGenerated(store,batch,'r1'),false);p.save(store,'custom second',base);assert.equal(p.replaceGenerated(store,batch,'r1'),false);assert(p.read(store).some(x=>x.name==='custom second'));console.log('PASS old generated presets replaced atomically while custom presets and revision survive');

const bal=require('../scripts/weight-balance.cjs');const configs=Array.from({length:15},(_,i)=>({name:'서울 균형 기준'+[3,4,9][Math.floor(i/5)]+' 파생 '+(i+1)+'번',settings:{anchorMode:'analysis',modelMode:'custom',min:2,max:6,weights:bal.project(Array(17).fill(1))}}));
const memory={data:null,getItem(){return this.data},setItem(k,v){this.data=v}};const api=require('../strategy-presets.js');api.replaceGenerated(memory,configs,'one');api.replaceGenerated(memory,configs,'two');assert.equal(api.read(memory).length,15);console.log('PASS balanced recommendation revisions replace instead of accumulating');
