const assert=require('node:assert/strict'),fs=require('node:fs'),model=require('../model.js'),t=require('../tuning-model.js'),presets=require('../strategy-presets.js'),history=require('../qpl-history-engine.js');
const {shift,quarter,blend,covers,evaluate,aggregate}=require('../scripts/rolling-search.cjs');
assert.equal(shift('20240101',-24),'20220101');assert.equal(quarter('20260915'),'20260701');assert(!covers({total:13032,evaluated:5212}));assert(covers({total:13032,evaluated:5213}));
const a=Array(16).fill(0),b=Array(16).fill(0);a[13]=100;b[14]=100;assert(blend(a,b,50)[14]>blend(a,b,5000)[14]);assert.equal(blend(a,b,50).reduce((a,b)=>a+b,0),100);
function race(venue){return {date:'20250101',venue,race_no:1,horses:Array.from({length:8},(_,i)=>({number:i+1,name:'H'+i,rating:30+i,weighted_v3_features:Array.from({length:16},(_,j)=>j===13?i/7:j===14?1-i/7:.5),weighted_features:Array(13).fill(.5)})),official_result:{starters:[1,2,3,4,5,6,7,8],pair:{status:'confirmed',payouts:[{numbers:[1,8],odds:4}]}}};}
const market={quotes:Array.from({length:8},(_,i)=>({numbers:[i+1],odds:1+(i+1)/10}))};const config={modelMode:'custom',anchorMode:'analysis',weights:a,min:2,max:4,weightScope:'venue',venueWeights:{seoul:b,busan:a,jeju:a}};
assert.equal(t.apply(model.analyze(race('seoul')),config).places[0].numbers[0],1);assert.equal(t.apply(model.analyze(race('busan')),config).places[0].numbers[0],8);
const row=t.pack(model.analyze(race('seoul')),market),original=JSON.stringify(row);const evalr=history.create([row]);const x=evalr.evaluateRow(0,config);const changed=structuredClone(config);changed.venueWeights.seoul=a;const y=evalr.evaluateRow(0,changed);assert.notEqual(x.candidates[0].partner.number,y.candidates[0].partner.number);assert.equal(JSON.stringify(row),original);
const storage={data:{},getItem(k){return this.data[k]||null},setItem(k,v){this.data[k]=v}};presets.save(storage,'regional',config);assert.deepEqual(presets.read(storage)[0].settings,config);assert.throws(()=>presets.config({...config,venueWeights:{seoul:Array(16).fill(0)}}));
assert.equal(t.settings({modelMode:'custom',weights:Array(13).fill(1)}).modelMode,'v2');assert.equal(t.settings({modelMode:'custom',weights:Array(10).fill(1)}).modelMode,'legacy');
const manifest=JSON.parse(fs.readFileSync('qpl-history.json'));let n=0;for(const s of manifest.shards)for(const r of JSON.parse(fs.readFileSync(s.url)).rows){for(const h of r.horses){assert.equal(h[6]?.length,16);assert(h[6].every(x=>x>=0&&x<=1));if(h[7]?.through)assert(h[7].through<r.date);}n++;}
console.log('PASS rolling date boundaries, source-universe coverage, shrinkage, venue-specific probability/cache, saved settings migration and',n,'feature rows');
