const fs=require('node:fs'),assert=require('node:assert/strict'),crypto=require('node:crypto'),t=require('../tuning-model.js'),p=require('../strategy-presets.js'),{evaluate}=require('../scripts/rolling-search.cjs');
const {RULES,pairDistance,rangeKey,bandKey}=require('../scripts/preset-diversity.cjs'),policy=require('../qpl-policy.js');
const report=JSON.parse(fs.readFileSync('top5-presets.json')),manifest=JSON.parse(fs.readFileSync('qpl-history.json'));
assert.equal(report.scope,'seoul');assert.equal(report.version,t.VERSION);assert.equal(report.presets.length,10);assert.equal(report.minimumCoverageRatio,.4);assert.equal(report.minimumEvaluated,Math.ceil(report.sourceRaces*.4));
const rows=manifest.shards.flatMap(s=>JSON.parse(fs.readFileSync(s.url)).rows).filter(r=>r.date>=report.from&&r.date<=report.to);assert.equal(rows.length,report.sourceRaces);assert(rows.every(r=>r.venue==='seoul'));
assert.deepEqual(report.selectionRules,RULES);const vectors=[],ranges=new Map(),bands=new Map();const hashes=new Set();let previous=Infinity;
for(const preset of report.presets){assert(preset.all.hits*10>=preset.all.evaluated);assert(preset.metrics.product>=report.bestEligibleProduct*RULES.minimumProductRatio);ranges.set(rangeKey(preset),(ranges.get(rangeKey(preset))||0)+1);bands.set(bandKey(preset),(bands.get(bandKey(preset))||0)+1);const vector=new Uint16Array(rows.length);for(let i=0;i<rows.length;i++){const row=rows[i];if(!row.settled)continue;const result=policy.apply(t.apply(t.unpack(row),preset.settings),{quotes:row.quotes},preset.settings);if(result.qplPolicy.status==='ready'){const ns=result.pairs[0].numbers.slice().sort((a,b)=>a-b);vector[i]=ns[0]*32+ns[1];}}assert.equal(crypto.createHash('sha256').update(Buffer.from(vector.buffer)).digest('hex'),preset.predictionHash);vectors.push(vector);assert.deepEqual(p.config(preset.settings),preset.settings);assert.equal(preset.settings.weights.length,16);assert.equal(preset.settings.weights.reduce((a,b)=>a+b,0),100);assert(preset.all.evaluated>=report.minimumEvaluated);assert(preset.metrics.product<=previous);previous=preset.metrics.product;hashes.add(preset.predictionHash);
 const x=evaluate(rows,preset.settings);assert.deepEqual(x.all,preset.all);assert.equal(x.metrics.product,preset.metrics.product);assert.equal(x.metrics.average,preset.metrics.average);
 assert.equal(Object.values(preset.years).reduce((n,g)=>n+g.evaluated,0),preset.all.evaluated);
}
assert.equal(hashes.size,10);assert([...ranges.values()].every(n=>n<=2));assert([...bands.values()].every(n=>n<=4));for(let i=0;i<10;i++){let nearest=1;for(let j=0;j<10;j++)if(i!==j){const d=pairDistance(vectors[i],vectors[j]);assert(d+1e-12>=.1);nearest=Math.min(nearest,d);}assert.equal(nearest,report.presets[i].nearestPairDifference);}console.log('PASS ten diverse Seoul presets with >=10% hit rate and >=10% pair difference: exact full-history metrics, descending product, integer weights totaling 100%, >=40% source coverage and valid saved configurations');
